# Generated by Django 3.1.2 on 2020-10-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_first_name', models.CharField(max_length=255)),
                ('candidate_last_name', models.CharField(max_length=255)),
                ('candidate_email_address', models.EmailField(max_length=128, null=True)),
            ],
        ),
    ]
