# Generated by Django 3.1.2 on 2020-10-12 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='job_poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='offer_accepted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='salary_offer',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='candidate_first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='candidate_last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
