# Generated by Django 3.1.2 on 2020-10-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0002_auto_20201012_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='offer_accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='salary_offer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
