# Generated by Django 3.1.2 on 2020-10-14 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_offers', '0003_auto_20201012_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='job_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
